apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-init"
  namespace: {{ .Values.namespace }}
data:
  00-init-user.sql: |
    CREATE USER program WITH PASSWORD 'test';
    ALTER USER program CREATEDB;
    
  01-create-databases.sql: |
    CREATE DATABASE tickets OWNER program;
    CREATE DATABASE flights OWNER program;
    CREATE DATABASE privileges OWNER program;
    
    GRANT ALL PRIVILEGES ON DATABASE tickets TO program;
    GRANT ALL PRIVILEGES ON DATABASE flights TO program;
    GRANT ALL PRIVILEGES ON DATABASE privileges TO program;

  02-tickets-schema.sql: |
    \c tickets;
    CREATE TABLE IF NOT EXISTS ticket
    (
        id            SERIAL PRIMARY KEY,
        ticket_uid    uuid UNIQUE NOT NULL,
        username      VARCHAR(80) NOT NULL,
        flight_number VARCHAR(20) NOT NULL,
        price         INT         NOT NULL,
        status        VARCHAR(20) NOT NULL
            CHECK (status IN ('PAID', 'CANCELED'))
    );
    ALTER TABLE ticket OWNER TO program;

  03-flights-schema.sql: |
    \c flights;
    CREATE TABLE IF NOT EXISTS airport
    (
        id      SERIAL PRIMARY KEY,
        name    VARCHAR(255),
        city    VARCHAR(255),
        country VARCHAR(255)
    );
    ALTER TABLE airport OWNER TO program;

    CREATE TABLE IF NOT EXISTS flight
    (
        id              SERIAL PRIMARY KEY,
        flight_number   VARCHAR(20)              NOT NULL,
        datetime        TIMESTAMP WITH TIME ZONE NOT NULL,
        from_airport_id INT REFERENCES airport (id),
        to_airport_id   INT REFERENCES airport (id),
        price           INT                      NOT NULL
    );
    ALTER TABLE flight OWNER TO program;

    INSERT INTO airport(id, name, city, country) VALUES 
    (1, 'Шереметьево', 'Москва', 'Россия'),
    (2, 'Пулково', 'Санкт-Петербург', 'Россия')
    ON CONFLICT (id) DO NOTHING;

    INSERT INTO flight(id, flight_number, datetime, from_airport_id, to_airport_id, price)
    VALUES (1, 'AFL031', '2021-10-08 20:00', 2, 1, 1500)
    ON CONFLICT (id) DO NOTHING;

  04-privileges-schema.sql: |
    \c privileges;
    CREATE TABLE IF NOT EXISTS privilege
    (
        id       SERIAL PRIMARY KEY,
        username VARCHAR(80) NOT NULL UNIQUE,
        status   VARCHAR(80) NOT NULL DEFAULT 'BRONZE'
            CHECK (status IN ('BRONZE', 'SILVER', 'GOLD')),
        balance  INT
    );
    ALTER TABLE privilege OWNER TO program;

    CREATE TABLE IF NOT EXISTS privilege_history
    (
        id             SERIAL PRIMARY KEY,
        privilege_id   INT REFERENCES privilege (id),
        ticket_uid     uuid        NOT NULL,
        datetime       TIMESTAMP   NOT NULL,
        balance_diff   INT         NOT NULL,
        operation_type VARCHAR(20) NOT NULL
            CHECK (operation_type IN ('FILL_IN_BALANCE', 'DEBIT_THE_ACCOUNT'))
    );
    ALTER TABLE privilege_history OWNER TO program;